on: [push]
name: ARM build

jobs:
  linux_arm7:
    name: Linux ARM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: aarch64-unknown-linux-gnu
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target aarch64-unknown-linux-gnu
      - uses: actions/upload-artifact@v2
        with:
          name: counter-rocket-aarch64-linux
          path: target/aarch64-unknown-linux-gnu/release/counter-rocket
